### ISSUE TITLE
Keras to ONNX

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [leodestiny/onnx-keras#2]
Hello @leodestiny @xdyllx 

Great work!
I had few questions:
1. Are there any plan to convert Keras-ONNX. So that we enable people using Keras to move to PyTorch or MXNet for example? If not, if you can share some learnings, I am happy to jump in and contribute along with my friend (@roywei https://github.com/roywei)
2. Based on your current work, are there any list of missing/incompatible operators/layers between ONNX/Keras?

Thanks,

**Comment by leodestiny** [comment]
backend.py is module that converts from ONNX to Keras.
frontend.py is module that converts from Keras to ONNX.
Frontend is almost done, it can convert some famous models like DenseNet, but converted results are not tested in other frameworks to check whether results are right or wrong.
Backend needs some days to complete. We are in progress.
Indeed, there are some missing or incompatible operators between Keras and ONNX. Maybe, after complete backend, we can summarize a document.
Thanks for attention! Any suggestion is welcome.
